package es.telefonica.mimovistar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-07-22T10:45:45.063+02:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "urn:es:telefonica:mimovistar", name = "MiMovistarPortType")
@XmlSeeAlso({ es.telefonica.mimovistar.types.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MiMovistarPortType
{

	@WebResult(name = "eventoContadorPromocionesResponse", targetNamespace = "urn:es:telefonica:mimovistar:types", partName = "parameters")
	@WebMethod(action = "eventoContadorPromociones")
	public es.telefonica.mimovistar.types.EventoContadorPromocionesResponseType eventoContadorPromociones(@WebParam(partName = "parameters", name = "eventoContadorPromociones", targetNamespace = "urn:es:telefonica:mimovistar:types") es.telefonica.mimovistar.types.EventoContadorPromocionesType parameters);

	@WebResult(name = "eventoUmbralPromocionesResponse", targetNamespace = "urn:es:telefonica:mimovistar:types", partName = "parameters")
	@WebMethod(action = "eventoUmbralPromociones")
	public es.telefonica.mimovistar.types.EventoUmbralPromocionesResponseType eventoUmbralPromociones(@WebParam(partName = "parameters", name = "eventoUmbralPromociones", targetNamespace = "urn:es:telefonica:mimovistar:types") es.telefonica.mimovistar.types.EventoUmbralPromocionesType parameters);
}
